allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
minimumReleaseAgeExclude:
  - '@sokol111/ecommerce-category-query-service-api@1.0.20'
  - '@sokol111/ecommerce-product-query-service-api@1.0.20'
